### ISSUE TITLE
redux-immutable

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/web-boilerplate#56]
We should add `immutable` and `redux-immutable` to package.json, and we should change the top-level reducer to use that version of combineReducers

**Comment by leeallen337** [comment]
Hm. Should we include `ImmutableJS` into the boilerplate? I think it was left out to make the boilerplate less opinionated _but_ we include it in all our projects anyways so it would take less time to spin everything up. What do you think?

**Comment by dkniffin** [comment]
I think we should just include it. For a while, we were debating whether to use immutable everywhere or not, but I think at this point the decision has been made

**Comment by leeallen337** [comment]
Good points 👍 

I also spoke with @keeganbrown on Slack about Immutable and he agreed about including it in the boilerplate. I'm going to close this and include a task for including ImmutableJS in https://github.com/smashingboxes/web-boilerplate/issues/64

Thanks @dkniffin
