### ISSUE TITLE
Move routes into a directory

### ISSUE THREAD

**Issue by dkniffin** [smashingboxes/web-boilerplate#57]
With react-router v4, routes can live in multiple files. I think it'd be good to have a routes folder, with an index.jsx that is pretty much what the Routes.jsx file is now. Then, it can import other route files in that directory for sub-routes.

**Comment by leeallen337** [comment]
I like this idea and I'm doing this on `roamd-fe`. I'm adding it to https://github.com/smashingboxes/web-boilerplate/issues/64
